theme = "boo_berry"

[editor]
bufferline = "multiple"
mouse = true
true-color = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding"]

[keys.normal.space]
g = ":run-shell-command lantern-lazygit"

[keys.normal]
C-a = [":lantern-export-symbol-context", ":run-shell-command lantern-focus-agent"]

[keys.select]
C-a = [":lantern-export-symbol-context", ":run-shell-command lantern-focus-agent"]
