gui:
  mouseEvents: true
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  theme:
    activeBorderColor:
      - "#C7B8E0"
    inactiveBorderColor:
      - "#5A3D6E"
    searchingActiveBorderColor:
      - "#7FC9AB"
    optionsTextColor:
      - "#886C9C"
    selectedLineBgColor:
      - "#47345E"
    inactiveViewSelectedLineBgColor:
      - "#3A2A4D"
    unstagedChangesColor:
      - "#D678B5"
    defaultFgColor:
      - "#C7B8E0"
