theme = "lantern"

[editor]
bufferline = "multiple"
mouse = true
true-color = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "position"]

[keys.normal.space]
g = ":run-shell-command lantern-git"
e = ":run-shell-command lantern-focus-explorer"

[keys.normal]
C-a = [":lantern-export-symbol-context", ":run-shell-command lantern-agent-composer"]
F2 = ":run-shell-command lantern-toggle-agent"

[keys.select]
C-a = [":lantern-export-symbol-context", ":run-shell-command lantern-agent-composer"]
F2 = ":run-shell-command lantern-toggle-agent"
